### ISSUE TITLE
Erro ao realizar upload do exame

### ISSUE THREAD

**Issue by GabrielPintoSouza** [nilsonLazarin/WeGIA#10]
PDOException: SQLSTATE[HY000]: General error: 1364 Field 'data' doesn't have a default value in /var/www/html/WeGIA/html/saude/exame_upload.php:34
Stack trace:
#0 /var/www/html/WeGIA/html/saude/exame_upload.php(34): PDOStatement->execute()
#1 {main}

**Comment by GabrielPintoSouza** [comment]
array(1) {
  ["id_fichamedica"]=>
  string(1) "2"
}


Warning:  Undefined variable $id_docfuncional in /var/www/html/WeGIA/html/saude/exame_upload.php on line 29

Houve um erro ao realizar o upload do exame:

PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'id_exame_tipos' cannot be null in /var/www/html/WeGIA/html/saude/exame_upload.php:37
Stack trace:
#0 /var/www/html/WeGIA/html/saude/exame_upload.php(37): PDOStatement->execute()
#1 {main}

**Comment by GabrielPintoSouza** [comment]
array(2) {
  ["id_docfuncional"]=>
  string(1) "6"
  ["id_fichamedica"]=>
  string(1) "2"
}
Houve um erro ao realizar o upload do exame:

PDOException: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '23/02/2024' for column `wegia`.`saude_exames`.`data` at row 1 in /var/www/html/WeGIA/html/saude/exame_upload.php:37
Stack trace:
#0 /var/www/html/WeGIA/html/saude/exame_upload.php(37): PDOStatement->execute()
#1 {main}
