### ISSUE TITLE
Erro ao realizar upload de documento.

### ISSUE THREAD

**Issue by GabrielPintoSouza** [nilsonLazarin/WeGIA#16]
array(2) {
  ["id_docfuncional"]=>
  string(1) "1"
  ["idatendido"]=>
  string(1) "4"
}
Houve um erro ao realizar o upload do documento:

PDOException: SQLSTATE[HY000]: General error: 1364 Field 'data' doesn't have a default value in /var/www/html/WeGIA/html/atendido/documento_upload.php:40
Stack trace:
#0 /var/www/html/WeGIA/html/atendido/documento_upload.php(40): PDOStatement->execute()
#1 {main}

**Comment by GabrielPintoSouza** [comment]
array(2) {
  ["id_docfuncional"]=>
  string(9) "undefined"
  ["idatendido"]=>
  string(1) "3"
}
Houve um erro ao realizar o upload do documento:

PDOException: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: 'undefined' for column `wegia`.`atendido_documentacao`.`atendido_docs_atendidos_idatendido_docs_atendidos` at row 1 in /var/www/html/WeGIA/html/atendido/documento_upload.php:43
Stack trace:
#0 /var/www/html/WeGIA/html/atendido/documento_upload.php(43): PDOStatement->execute()
#1 {main}
